### ISSUE TITLE
webcam_restartfeed spec uses 'msg' instead of 'message'

### ISSUE THREAD

**Issue by tbird20d** [TimesysGit/board-farm-rest-api#12]
Most spec files use 'message' as the return message when a problem occurs.  However, spec/usb_webcam/webcam_restartfeed.yaml uses 'msg', and there is no 'result' field.

**Comment by harishbansal** [comment]
Fixed in pull request (https://github.com/TimesysGit/board-farm-rest-api/pull/16)
